### ISSUE TITLE
Error message when booting merged.efi

### ISSUE THREAD

**Issue by arun54321** [gmes78/sigen#1]
I get error during boot.
`initramfs unpacking failed. decoding failed.`
still system boots and functions normally.

**Comment by MonterraByte** [comment]
Can you include more info, such as the `sigen` command you used to create the merged EFI file?

**Comment by arun54321** [comment]
sudo ./sigen -c /proc/cmdline -i /tmp/merge.img -k /boot/vmlinuz-linux-ck-skylake -o /boot/out.efi

**Comment by arun54321** [comment]
cat /proc/cmdline
`initrd=\intel-ucode.img initrd=\initramfs-linux-ck-skylake.img root=UUID=xxx rootfstype=f2fs rw nowatchdog quiet
`
my initramfs is compressed with lz4.

**Comment by MonterraByte** [comment]
Note: you can pass the `-i` flag multiple times, `sigen` will merge the initramfs for you.

What's causing the issue is the `initrd=\intel-ucode.img initrd=\initramfs-linux-ck-skylake.img` part of the cmdline. You do not need to pass `initrd` flags for the initramfs files included in the EFI executable.

**Comment by arun54321** [comment]
Can I use something like this? 
`./sigen -i /boot/intel-ucode.img -i /boot/initramfs-linux-ck-skylake.img -c /tmp/cmdline -k /boot/vmlinuz-linux-ck-skylake -f -o /boot/out.efi
`
I have removed initrd parts in cmdline file.

```
cat /tmp/cmdline 
root=UUID=xxx rootfstype=f2fs rw nowatchdog quiet
```

**Comment by MonterraByte** [comment]
That should be good.

**Comment by arun54321** [comment]
It works. Thankyou.

**Comment by MonterraByte** [comment]
I've added a usage example to the README, to avoid future confusion.

I've also added an example on how to automate the whole process, in case you're interested.
